### ISSUE TITLE
Organize the repository and clean the source code

### ISSUE THREAD

**Issue by 0x0584** [0x0584/Lem-in#2]

**Comment by 0x0584** [comment]
Merge bauom/Lem-in's visualizer

**Comment by 0x0584** [comment]
### TODOs

+ [ ] #2: split the code structure into abstractions, 
      + at least we there's a data structure part: `queue.c`, `graph.c` ~~might add a `qnode.c` when norming~~
      + and an algorithmic part: `bfs.c`, `netflow.c` ~~might add a `flow.c`, `sync.c`~~
      + there's also the parsing abstraction: `parsing.c`, `get_lines.c`
+ [ ] #4: free all memory leaks
+ [x] ~~test the algorithm correctness~~
