### ISSUE TITLE
Enumerate the ants

### ISSUE THREAD

**Issue by 0x0584** [0x0584/Lem-in#5]
## About
 
printing the paths one edge a a time, if paths differ in size, then we'll _need some calculation before sending all ants_. (see #1 and #3)

**Comment by 0x0584** [comment]
## About

After re_wiring the paths, we have have got an optimal *network flow* from the *source* to the *sink*

| path 1 | path 2 | path 3 |
| ------------- |--------------| ----------|
| ![p1](https://user-images.githubusercontent.com/4406704/71326416-f5a6e180-24fa-11ea-9c24-7b78c6f1a1c8.png) | ![p2](https://user-images.githubusercontent.com/4406704/71326432-196a2780-24fb-11ea-88dc-5561d7c19e86.png) | ![p3](https://user-images.githubusercontent.com/4406704/71326438-20913580-24fb-11ea-83a3-18adc70ff6b6.png) |

## ~~Capacity scaling~~ Maximum flow and the least number of instructions

> Given all ants at the *source*, indeed (the edge which has `node_src` as *source*) with a goal of arriving at the *sink* (the edge which has `node_dst` as *sink*) with the least number of instructions
>
> *An instruction moving one or more ants one edge forward, as the paths are all lists of edges*

**Comment by 0x0584** [comment]
## TODOs

 * [x] ~~print names of arriving ants too~~
 * [x] ~~fix the names of on-going ants~~
 * [x] ~~get maxflow in terms least-instructions that's only getting max flows to sync per time~~
 * [x] ~~print all the ants that are going through the graph at each moment~~

**Comment by 0x0584** [comment]
## Flow synchronization in a flow network

the way the flow network is represented is as `struct s_flow` and `struct  s_netflow`.  each flow has a `current`, `mask`, number of `arriving` ants, and a boolean to `cut` the flow. the network itself has a queue of `flows` to _sync-in_ and a queue of `sync` to _sync-out_.

```c
#define FLOW_SATURATED(f)       ((f->current & f->cmask) == f->cmask)
struct s_flow
{
	t_edge			**path;    /* path as array of edges, see #1 and #3 */
	unsigned		latency;   /* length of the array */
	unsigned		current;   /* the flow status */
	unsigned		cmask;     /* current mask */
	bool			cut;       /* if true, this flow is */
	size_t			n_synced;  /* number of bits that have arrived */
	size_t			chunk;     /* the last chunk that have arrived */
};

struct s_flow_network
{
	t_queue			*flows; /* a queue of flows to sync-in */
	t_queue			*sync; /*a queue of flows to sync out */
	size_t			n_units; /* units to send through the network */
	size_t			maxflow;  /* maximum flow of the network */
};
```

### Establishing a Flow Network

> Given a graph `G(V,E)`, the flow network `N(V, F)` is a sub graph of `G` where `F` is a set containing _only the edges that are part of paths that lead from the source to the sink_. 

We setup a flow network based on a given graph using `netflow_setup(g, units)`, which extract the set of all possible paths that can lead from the source to the sink, starting by the shortest using `bfs_find()` (see #1), then rewire the paths (see #3), which would be enqueued based on their flow latency (number of edges). 

### Adjusting the flow network

Some times, we have a number of units that would arrived sooner if sent through shortest flows, ie. we have to cut some flows as we transmit bits. `netflow_shrink()` adjusts the flow so that ~~_we can send as `queue_size(net->flows)` ants as per time, but when the number of _remaining ants is less than the number of flows_  send as many `maxflow`. and all other flows, ie. `queue_size(net->flows) - maxflow` are cuted._~~ As far as a the _flow's latency is less or equal the number of units_ or _it's latency is equal to the latency of the previous flow_, it's suitable. 

Since we're only enqueuing those two kinds of flows to ensure that we will always `sync-in` the flow as quick a possible. Once we've reached some _a flow that does not meet those two requirements_, we enqueue it and all the `flows` that have latency above its `latency` to `net->sync`, after setting them as `cut`'d, to indicate they're to be synced out.

> * the queue `net->flows` always got at least one flow, indeed the one with lower latency
> * If we have no more units, we enqueue all the `net->flows` to the `net->sync`

### The process of synchronization

This is the process of pushing flow through the network. `netflow_sync()` is the main function, it has two roles, since the `flows` and the `sync` queues are both sorted with priority to lower `latency`

 * **sync-in the flows** _while there is unites from tail of the queue_
 * **sync-out the sync**  _all syncs starting from the head of the queue_

`netflow_sync()` returns a `state` to indicate that the flow is still going, which means we either _sync-in_ or _sync-out_, ie. the flow is still going. We terminate when the state is `false`

### The maximum possible flow

> The flow is going through the network as based on *how many ants we still have, and how max flow we can reach*. 

Given `N` ants, and we want to select which *flow* in the queue `net->flows` we're going to take. The flows are sorted, from lower to higher (from tail to head), selecting flows with *lower latency* first.

while we still moving from tail towards the head of the queue, do

  * if the latency of the flow is _less than the remaining number of ants_, or _equal to the previous flow's latency_, then, augment *net->maxflow* with the latency of the current *flow*. **continue**
  * else, _dequeue all flows that are higher or equal_ to the current flow's latency. **break**

 *Shrinking the network* that way will always guarantee that we are achieving the *maxflow* 

### Enumerating the ants

> The ants represent _the bits of flow that are going_, where each flow will receive an ant with a different number: `L5-bar` means that the ant (bit)`5` now is at room (node) `bar`.

The names of the ants are _modulo of with the flow's index in the queue_. If we have a flow network with `5` initial flows, then

 * flow 0 would have **mod 5** ants: 0 5 10 15 ...
 * flow 1 would have **mod 5 + 1** ants 1 6 11 16 ... 
 * flow 2 would have **mod 5 + 2** ants 2 7 12 17 ... 
 * flow 3 would have **mod 5 + 3** ants 3 8 13 18 ... 
 * flow 4 would have **mod 5 + 4** ants 4 9 14 19 ... 

> * *we have to store the last `chunk` within the flow to know which ants are going though*
> * *if a flow is `cut`'d means also that it won't receive any more `chunks`*
